## introduction to oop python
one of the popular approach to solve a programming problem by creating an objects , this is known as Object Oriented Programming

#### An object as two characterstics:
  1. Attribution(name,age,colour)
  2. Behaviour(learn,study,singing,dance)
  
#### In Python the concept OOP follow these things:
  1. Inheritence 
  2. Encapsulation
  3. Ploymorphism
  
#### Class: 
A class is blueprint for the object or logical entity
#### Object:
Blue print of class or Instance of the class or physical entity
#### methods:
part of class and can be called with 

class classmate:
    # some function and variables
    # function----used to perform the specific activity
    # variables--dat(memory)

In [2]:
def test():
    print('Test() for function')
    return
test()

Test() for function


In [3]:
class Demo:
    def test(self):
        print("test() for the class and method")
        return
obj = Demo()
obj.test()

test() for the class and method


In [7]:
class Demo1:
    def fact(self,n):
        #return the factorial
        fact = 1
        while(n!=0):
            fact = fact*n
            n = n-1
        return fact
p1 = Demo1()
p1.fact(5)

120

In [16]:
class Demo2:
    def __init__(self,p1,p2):
        self.p1 = p1
        self.p2 = p2
    def add(self,p1,p2):
        return p1+p2
c1 = Demo2(10,20)
print(c1.add(100,200))

300


In [23]:
class demo2:
    def accept(self,p1,p2):
        a=p1
        b=p2
        return
    def display(self,p1,p2):
        print("p1=",p1)
        print("p2=",p2)
c1 = demo2()
c1.accept(10,20)
c1.display(10,20)

p1= 10
p2= 20


In [28]:
# Some Inheritance
# Parent class
class person (object):
    #constructor
    def __init__(self,name):
        self.name = name
    def getname(self):
        return self.name
    def isemployee(self):
        return False

# Derived Class
class employee(person):
    def isemployee(self):
        return True
    
    emp = person("anil")
    print(emp.getname(),emp.isemployee())
    
    emp = person("akhil")
    print(emp.getname(),emp.isemployee())

anil False
akhil False


In [25]:
lst = [1,2,3,4]
print(lst)

[1, 2, 3, 4]


In [26]:
import numpy as np
lst = [1,2,3,4]
array = np.array(lst)
print(array)

[1 2 3 4]


In [32]:
lst = [1.0,2.5,3.6,9.5]
array = np.array(lst)
print(array.shape)
print(array.dtype)

(4,)
float64


In [39]:
a1 = np.array([(1,2,3),(4,5,6)])
print(a1.shape)
a2 = np.array([(1,2),(3,4),(5,6)])
print(a2.shape)

(2, 3)
(3, 2)


In [37]:
# Re-shape the given array
#numpy reshape(arrayName,reshape,order='c')
a1 = np.array([(1,2,3),(4,5,6)])
print(a1)
a1.reshape(3,2)

[[1 2 3]
 [4 5 6]]


array([[1, 2],
       [3, 4],
       [5, 6]])

In [43]:
# Append Some Data -- Horizontally
# hstack(array1,array2) -- will be automatically arranged in horizontally 
a1 = np.array([1,2,3])
a2 = np.array([4,5,6])
print(np.hstack((a1,a2)))

[1 2 3 4 5 6]


In [45]:
# Append Some Data -- vertical
# vstack(array1,array2) -- will be automatically arranged in vertically
a1 = np.array([1,2,3])
a2 = np.array([4,5,6])
print(np.vstack((a1,a2)))

[[1 2 3]
 [4 5 6]]


In [57]:
# Generate random number from NP
a1 = np.random.normal(5,0.5,10)
print(a1)

[4.12880116 5.71526739 4.84225551 4.93731502 4.17779902 4.84075574
 4.78954346 5.11701242 4.60215396 4.14558433]


In [60]:
# numpy.zeros() and numpy.one()
# generate an array with all zeros --numpy.zeros()
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [63]:
np.zeros((2,2),dtype=np.int64)

array([[0, 0],
       [0, 0]], dtype=int64)

In [65]:
np.ones((4,3),dtype=np.int64)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int64)

In [66]:
a=np.matrix(np.ones((4,4),dtype=np.int64))
np.asarray(a)[2][3] = 14
np.asarray(a)[3][3] = 16
print(a)

[[ 1  1  1  1]
 [ 1  1  1  1]
 [ 1  1  1 14]
 [ 1  1  1 16]]


In [67]:
import numpy as np
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [68]:
np.arange(1,100,9)

array([ 1, 10, 19, 28, 37, 46, 55, 64, 73, 82, 91])

In [70]:
np.arange(2,20,2)
np.arange(1,25,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23])

In [71]:
# Indexing and slicing of numpy
a1 = np.array([(1,2,3),(4,5,6)])
print(a1)

[[1 2 3]
 [4 5 6]]


In [72]:
a1 = np.array([(1,2,3),(4,5,6)])
print("First Row",a1[0])

First Row [1 2 3]


In [73]:
a1 = np.array([(1,2,3),(4,5,6)])
print("Second Row",a1[1])

Second Row [4 5 6]


In [74]:
a1 = np.array([(1,2,3),(4,5,6)])
print("slicing Row",a1[1])

slicing Row [4 5 6]


In [75]:
a1 = np.array([(1,2,3),(4,5,6)])
print("Row and Coloum",a1[1:2])

Row and Coloum [[4 5 6]]


In [77]:
a1 = np.random.normal(5,1,10)
print(a1)

[4.24536869 4.33854288 4.85076248 4.98556054 6.47085668 4.90049173
 6.79038588 6.05111829 5.81665356 3.85837635]


## Some Math Operation on given random numbers
#### Min ---returns the least number
#### max ---returns the large number
#### Mean ---Mean
#### Median ---Median
#### GD ---Gaussian Distribution

In [81]:
a1 = np.random.normal(5,1,10)
print(a1)
print("Min value = ",np.min(a1))
print("Max value = ",np.max(a1))
print("Mean value = ",np.mean(a1))
print("Median value = ",np.median(a1))

[4.75376994 5.87857428 5.15440148 5.22413979 2.21619867 4.75249221
 5.03722781 6.17832968 4.98886823 5.92073621]
Min value =  2.2161986723921983
Max value =  6.178329676440758
Mean value =  5.010473830082832
Median value =  5.095814643461253


#### Pandas Basics
 Python is one of the popular programming language for data analysis<br>
 python is offering the lib called pandas used for importing and analysing pretty much faster and easier
 
 Pandas data for

In [1]:
import pandas as pd
dict = {"name":["Anil","Akhil","dinesh","Harsha","Ajay","Kranth"],
       "EmailID":["anil@gmail.com","akhil@gmail.com","dinesh@gmail.com","harsha@gmail.com","ajay@gmail.com","kranth@gmail.com"],
       "Mobile number" : [77,88,99,66,55,44],
        "Address":["hyd","hyd","hyd","hyd","hyd","hyd"]}
b = pd.DataFrame(dict)
print(b)

     name           EmailID  Mobile number Address
0    Anil    anil@gmail.com             77     hyd
1   Akhil   akhil@gmail.com             88     hyd
2  dinesh  dinesh@gmail.com             99     hyd
3  Harsha  harsha@gmail.com             66     hyd
4    Ajay    ajay@gmail.com             55     hyd
5  Kranth  kranth@gmail.com             44     hyd


In [3]:
b.index=["1","2","3","4","5","6"]
print(b)

     name           EmailID  Mobile number Address
1    Anil    anil@gmail.com             77     hyd
2   Akhil   akhil@gmail.com             88     hyd
3  dinesh  dinesh@gmail.com             99     hyd
4  Harsha  harsha@gmail.com             66     hyd
5    Ajay    ajay@gmail.com             55     hyd
6  Kranth  kranth@gmail.com             44     hyd


# supermarket.csv - Analysis(Which product having higher % of selling) 
# which products having least selling %